### ISSUE TITLE
node-gyp rebuild fail on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by seoker** [lovell/farmhash#14]
Hi,

Nice module! I have tried on my local and everything works fine.
However, it gets rebuild fail when I was trying to deploying onto my AWS EB app, here's the partial log:
```
1058 verbose rebuildBundles farmhash@1.2.1
1059 info lifecycle farmhash@1.2.1~install: farmhash@1.2.1
1060 verbose lifecycle farmhash@1.2.1~install: unsafe-perm in lifecycle false
1061 verbose lifecycle farmhash@1.2.1~install: PATH: /opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/tmp/deployment/application/node_modules/farmhash/node_modules/.bin:/tmp/deployment/application/node_modules/.bin:/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin:/opt/elasticbeanstalk/lib/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
1062 verbose lifecycle farmhash@1.2.1~install: CWD: /tmp/deployment/application/node_modules/farmhash
1063 silly lifecycle farmhash@1.2.1~install: Args: [ '-c', 'node-gyp rebuild' ]
1064 silly lifecycle farmhash@1.2.1~install: Returned: code: 1  signal: null
1065 info lifecycle farmhash@1.2.1~install: Failed to exec install script
1066 verbose stack Error: farmhash@1.2.1 install: `node-gyp rebuild`
1066 verbose stack Exit status 1
1066 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
1066 verbose stack     at emitTwo (events.js:106:13)
1066 verbose stack     at EventEmitter.emit (events.js:191:7)
1066 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
1066 verbose stack     at emitTwo (events.js:106:13)
1066 verbose stack     at ChildProcess.emit (events.js:191:7)
1066 verbose stack     at maybeClose (internal/child_process.js:877:16)
1066 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
1067 verbose pkgid farmhash@1.2.1
1068 verbose cwd /tmp/deployment/application
1069 error Linux 4.4.23-31.54.amzn1.x86_64
1070 error argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "--production" "rebuild"
1071 error node v6.9.1
1072 error npm  v3.10.8
1073 error code ELIFECYCLE
1074 error farmhash@1.2.1 install: `node-gyp rebuild`
1074 error Exit status 1
1075 error Failed at the farmhash@1.2.1 install script 'node-gyp rebuild'.
1075 error Make sure you have the latest version of node.js and npm installed.
```

Any suggestion?

**Environment**: 64bit Amazon Linux 2016.09 v3.1.0 running Node.js
**Node.js version**: v6.9.1
**NPM version**: NPM 2.15.5

**Comment by lovell** [comment]
The most common problem with EB is that the `HOME` env var needs to be set.

https://github.com/nodejs/node-gyp/issues/414

http://stackoverflow.com/questions/34084814/npm-error-when-deploying-nodejs-to-elastic-beanstalk

**Comment by seoker** [comment]
Hi,

Thanks for the reply.
Just followed the instructions, but unfortunately it doesn't work. Even I tried creating a new test EB app, with only express & farmhash packages and config set (HOME/USERPROFILE var), the situation remains.

Any other idea? :(

**Comment by lovell** [comment]
The only other common problem I'm aware of with EB is around file permissions.

If EB is involving a root-level user anywhere the installation process then perhaps try something like `npm install --unsafe-perm` 

(I don't recommend [unsafe-perm](https://docs.npmjs.com/misc/config#unsafe-perm) unless absolutely necessary.) 

It's very unlikely this problem is specific to farmhash. Good luck!

**Comment by seoker** [comment]
Just tried https://github.com/mapnik/node-mapnik/issues/659, still no luck.. :(
I do believe it's something about `node-gyp` & `elasticbeanstalk`, but could I just leave this post here and see if any others facing this kind of issue like me? I'll give another tries and update here if any.

**Comment by limhanchung** [comment]
I'm having the same problem

**Comment by sagifogel** [comment]
I'm having the same problem on windows 7.

**Comment by lovell** [comment]
@sagifogel This issue is about Elastic Beanstalk. If you're having problems with Windows, please ensure you've installed [the prerequisites for node-gyp](https://github.com/nodejs/node-gyp#installation) before opening a new issue.

**Comment by florianbepunkt** [comment]
@seoker @limhanchung @sagifogel A little bit late to the party, but having the same problem. Has anyone of you found a solution for this?

**Comment by lovell** [comment]
https://github.com/lovell/sharp/issues/373#issuecomment-226849756 might be relevant here.

**Comment by florianbepunkt** [comment]
@lovell Thank you. I don't think so, I dont'have any node_modules in my folder I'm deploying, just the package.json

But I found that AWS has more detailed logs. In npm debug I have the same error as @seoker, but in another log, it's more detailed. For every binary it reads

Package Qt5Gui was not found in the pkg-config search path.
  Perhaps you should add the directory containing `Qt5Gui.pc'
  to the PKG_CONFIG_PATH environment variable

Not sure what it means though…

**Comment by zachariahtimothy** [comment]
FWIW, farmhash was failing using the node:7.9.0-alpine docker image for me.  I was able to add python, make, and g++ in my docker file to get this working. Seems crazy this is required, but it will get you running until a better solution can be provided.
If using docker, add the following to your Dockerfile, otherwise install these dependencies manually.

````
RUN apk update && \
    apk add python make g++
````

**Comment by lovell** [comment]
Pre-compiled binaries are now provided so most of the issues reported here should no longer occur. musl-based Linux distributions such as Alpine will still need node-gyp and its dependencies (python, make, g++).
