### ISSUE TITLE
SIGILL with latest farmhash

### ISSUE THREAD

**Issue by NuSkooler** [lovell/farmhash#18]
After updating to the latest `2.0.1` version, farmhash crashes for me in CentOS x64.

Details of system:
* OS: CentOS 7 x64
* Kernel: Linux 3.10.0-514.16.1.el7.x86_64
* Node.js version: 6.11.3

Small program that crashes (`index.js`):
```
console.log('before require');
const farmhash = require('farmhash');
function main() {
        console.log('before string');
        const art = 'abc'.repeat(1000);
        console.log('before hash');
        const hash = farmhash.hash32(art);
        console.log(hash);
}
main();
```

The above outputs:
```
node index.js
before require
before string
before hash
fish: “node index.js” terminated by signal SIGILL (Illegal instruction)
```

I tried this with a previous dot version of Node with the same results. The same code functions on my eOS (Ubuntu) x64 machine. Previous versions of farmhash worked on both.

**Comment by lovell** [comment]
Hello, is this occurring on a machine with an older CPU without AVX intrinsics?

> "Pre-compiled binaries are provided for CPUs with SSE4.2 and AVX intrinsics. Use the npm install --build-from-source flag to compile for other platforms." https://github.com/lovell/farmhash/blob/master/README.md

Perhaps these should be "downgraded" to SSE4.2 only?

**Comment by NuSkooler** [comment]
@lovell Ah, yes you're right:
```
$ grep avx /proc/cpuinfo
$
```

The problem now becomes `package.json`. I'm using farmhash a dependency of a project. Any idea how to specify this in `package.json` that is compatible with `npm` and `yarn`?

Downgrading to SSE4.2 only would also work well for my particular CPU: `Intel(R) Celeron(R) CPU  N2807  @ 1.58GHz`

**Comment by lovell** [comment]
Commit 8bc92c6 switches the prebuilt binaries to require SSE4.2 only. This is now available from npm as v2.0.2 so should "just work" after a fresh re-install, assuming the semver range is wide enough. Are you able to test?

**Comment by NuSkooler** [comment]
@lovell Gave it a shot with the same program in OP. Unfortunatnelly it yielded the same results. I removed the `node_modules`, set farmhash to `2.0.2` in `package.json` and re-ran `yarn` before doing this.

**Comment by lovell** [comment]
Ah, thanks for checking, best guess would be that the [CXXFLAGS](https://github.com/lovell/farmhash/blob/master/.travis.yml#L29) environment variable isn't being propagated correctly through prebuild-ci/prebuild/node-gyp. Have to take another look.

**Comment by lovell** [comment]
I had misread the Travis [docs](https://docs.travis-ci.com/user/environment-variables/#Global-Variables), commit 6fc3a78 should sort this.

**Comment by lovell** [comment]
v2.0.3 now available with binaries built using `CXXFLAGS="-march=corei7"`

**Comment by NuSkooler** [comment]
I hate to be the bearer of bad news, but that didn't work.

Removed `node_modules` -> update `package.json` inclusion of `farmhash` to 2.0.3 -> yarn -> run the test again: SIGILL.

Built from source via `npm rebuild --build-from-source farmhash` and re-ran the test script: worked.

[N2807 CPU](http://ark.intel.com/products/81072/Intel-Celeron-Processor-N2807-1M-Cache-up-to-2_16-GHz)

**Comment by lovell** [comment]
@NuSkooler Thanks for the update, sorry this didn't work. The N2807 does have SSE4.2. I'll try to emulate with QEMU to see if I can reproduce this locally.

**Comment by NuSkooler** [comment]
@lovell I'll see if I can come up with some decent flags as well. I've never separated by _specific_ architectures in gyp, but I imagine it can be done.

**Comment by NuSkooler** [comment]
@lovell Any update on this? I tried changing the arch flag to `-march=corei7` in my local .gyp file and re-building. Everything worked as expected. If the pre-built binaries were made the same way, I'm not sure why I'm not getting them.

**Comment by lovell** [comment]
I disassembled the `farmhash.node` file built on Travis and it contained AVX `vmovdqa` instructions.

The CXXFLAGS that were used to build this included, in the order they appear, `-march=native -march=corei7`. It looks like `gcc` is using the first of these to auto-enable `-mavx` but then not switching it off again with the second.

I added an explicit `-mno-avx` in commit 76ac6ef and the resulting `farmhash.node` no longer contains `vmovdqa` instructions. I did however spot an `aesimc` instruction, so will need to add `-mno-aes -mno-f16c` flags also.

**Comment by lovell** [comment]
v2.0.4 now published with this change, fingers crossed etc.

**Comment by NuSkooler** [comment]
@lovell Thanks for taking the time to go hardcore instruction digging on this thing! It's working like a champ on my box now!

**Comment by lovell** [comment]
😅

**Comment by rbustami** [comment]
@lovell This seems to be an issue again with the latest release for farmhash

**Comment by lovell** [comment]
@rbustami Please can you provide details of the platform (e.g. Windows, Linux) and CPU (e.g. the output of `cat /proc/cpuinfo`) you're experiencing this with.
