### ISSUE TITLE
fingerprint64 doesn't match java implementation

### ISSUE THREAD

**Issue by scott-phillips** [lovell/farmhash#27]
Howdy,

I'm trying to use this library to match a same hash function using google common hash implemented in java, but I can't seem to get the same results on either platform.

Here's the java implementation:
```
import com.google.common.hash.HashFunction;
import com.google.common.hash.Hasher;
import com.google.common.hash.Hashing;

HashFunction hf = Hashing.farmHashFingerprint64();
Hasher hasher = hf.newHasher().putBytes("foo".getBytes());

Assert.assertEquals("e383932f606f5c55", hasher.hash().toString());
```

Here's a node implementation:
```
import * as farmhash from 'farmhash'

const result = farmhash.fingerprint64(Buffer.from('foo'));

expect(Number(result).toString(16)).toBe('555c6f602f938400');
```

Why does the node result not match the java result?

**Comment by scott-phillips** [comment]
So I found the cause, the java implementation has a non intuitive toString() method.

https://github.com/google/guava/blob/master/guava/src/com/google/common/hash/HashCode.java#L413

**Comment by lovell** [comment]
Please note that the JavaScript `Number` type does not support 64 bit integers, hence `fingerprint64` returning a string, so `Number(result)` will lose precision without warning.

In this example, `result` is `6150913649986995171` but  `Number(result)` is `6150913649986995000`.

**Comment by scott-phillips** [comment]
Thanks lovell,

I've used BigInt, the stage 3 proposal that is in node 10.4+. And then matched java's big endian format. For anyone else running into this problem here's what I have that works.

```
const hash = farmhash.fingerprint64('foo');

let hex = BigInt(hash).toString(16);
// I think all farm hashes will be an even number of bytes, but I'm not 100%....
if (hex.length % 2) { hex = '0' + hex; } 

let bigEndian = '';
for ( let i = hex.length; i >= 2; i = i - 2) {
    bigEndian += hex.substring(i - 2, i);
}

expect(bigEndian).toBe('e383932f606f5c55');
```
