### ISSUE TITLE
fingerprint64 fails at runtime on node:10.15.3-alpine docker (Intel Xeon on AWS)

### ISSUE THREAD

**Issue by ashenwgt** [lovell/farmhash#28]
Hi, 

Thanks for creating this awesome module.

This has been working nicely on Windows and Ubuntu local machines, but got an issue on Docker running on AWS.

Issue: At runtime, it fails when calling fingerprint64 function. 

Environment details:
```
Docker Image: node:10.15.3-alpine
AWS Instance Type: GPU G3
Processor: Intel Xeon E5-2686 v4

farmhash version: 3.0.0
```

Does anyone have an idea on the root cause for this?

**Comment by lovell** [comment]
Hi, are you able to expand on what "it fails" means. How does it fail? Is there an error? Is there a crash? If a crash, what's the backtrace?

What's the output of running `cat /proc/cpuinfo | grep flags` inside the container?

You mention the musl-based Alpine. Are you able to test on a glibc-based Linux such as Debian?

**Comment by ashenwgt** [comment]
```

**Comment by ashenwgt** [comment]
The docker container crashes every time the fingerprint64 function gets called at runtime. No errors could be found in the container logs (stdout). 

Sorry, I don't know how to get the backtrace in this scenario. If you can explain it, I can recreate this issue and extract the information you need. 

```
$ cat /proc/cpuinfo | grep flags
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
```

Thanks for the tip, I will test it on Debian/Ubuntu containers too.

**Comment by lovell** [comment]
Thanks. Is Alpine Linux also being used at `npm install` time? (The prebuilt binaries are specific to each libc implementation, which is detected at install time.)
