### ISSUE TITLE
[question] Is Node 8 unsupported in v3.0.0?

### ISSUE THREAD

**Issue by micburks** [lovell/farmhash#29]
From what I can tell by looking at the commits, removing support for Node 8 was an afterthought when releasing `farmhash@3.0.0`. I'm migrating a library to Node 12 and don't want to necessarily drop support for v8. If I `yarn install --ignore-engines` with Node 8 and farmhash 3, everything builds fine. I just wanted to see why support for Node 8 was dropped other than it leaving active LTS status. It's still in maintenance LTS at the moment, so it'd be great to allow, if possible

**Comment by lovell** [comment]
Yes, the migration to N-API in #20 revealed that the implementation of N-API in Node.js 8 (and the various versions of Electron that purport to be ABI compatible with it) not stable enough.

I recommend sticking to farmhash v2 if you still require Node.js 8 support.

The benefit of using farmhash v3 and N-API is that you won't need to rebuild/reinstall when migrating from Node.js 10 to 12 (to 14 etc).

**Comment by micburks** [comment]
Ah! I didn't realize farmhash v2 supported Node 12. That's great, thanks for the help!
