### ISSUE TITLE
undefined symbol: napi_add_finalizer

### ISSUE THREAD

**Issue by iravishah** [lovell/farmhash#34]
Farmhouse verison 3.1.0
Node version 8.16.0.

**Comment by lovell** [comment]
Support for Node.js 8 was removed in v3.0.0 via commit https://github.com/lovell/farmhash/commit/a88bfec4c8d9bbcf07aba206910bf3ad04548ac2

https://github.com/lovell/farmhash/blob/master/package.json#L38
