### ISSUE TITLE
Crashes on heroku for hash of 8 characters or larger.

### ISSUE THREAD

**Issue by mishugana** [lovell/farmhash#35]
When running on a Heroku dyno, the farmhash prebuilt-install binary that gets downloaded crashes with an **Illegal Instruction** 
it actually only happens when calling any Hash function for strings of 8 characters or longer.

It seems to be using:
[farmhash-v3.1.0-napi-v3-linux-x64.tar.gz]
(https://github.com/lovell/farmhash/releases/download/v3.1.0/farmhash-v3.1.0-napi-v3-linux-x64.tar.gz)

Running uname --kernel-name --kernel-release --machine gives me: 
**Linux 4.4.0-1078-aws x86_64**

Node version : **v12.18.4**

proc/cpuinfo gives me: 

> processor	: 0
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 0
> cpu cores	: 4
> apicid		: 0
> initial apicid	: 0
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:
> 
> processor	: 1
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 1
> cpu cores	: 4
> apicid		: 2
> initial apicid	: 2
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:
> 
> processor	: 2
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 2
> cpu cores	: 4
> apicid		: 4
> initial apicid	: 4
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:
> 
> processor	: 3
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 3
> cpu cores	: 4
> apicid		: 6
> initial apicid	: 6
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:
> 
> processor	: 4
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 0
> cpu cores	: 4
> apicid		: 1
> initial apicid	: 1
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:
> 
> processor	: 5
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 1
> cpu cores	: 4
> apicid		: 3
> initial apicid	: 3
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:
> 
> processor	: 6
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 2
> cpu cores	: 4
> apicid		: 5
> initial apicid	: 5
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:
> 
> processor	: 7
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 62
> model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
> stepping	: 4
> microcode	: 0x42e
> cpu MHz		: 2494.102
> cache size	: 25600 KB
> physical id	: 0
> siblings	: 8
> core id		: 3
> cpu cores	: 4
> apicid		: 7
> initial apicid	: 7
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
> bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
> bogomips	: 4988.20
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:

**Comment by lovell** [comment]
I'd expect the prebuilt binaries to "just work" on Intel Ivy Bridge CPUs such as the E5-2670 v2 as they support the `sse4_2` flag.

Have you tried `npm install --build-from-source`? You should see greater performance improvements due to the ability to use AVX intrinsics.

**Comment by dlazares** [comment]
Hey any ideas/updates on how to fix this?

**Comment by lovell** [comment]
The compiler flags used to create the prebuilt binaries are:

https://github.com/lovell/farmhash/blob/32cc9728309ab88a6e16a31d6ee4081fa01a2a30/.github/workflows/ci.yml#L53

I think newer versions of gcc have renamed this CPU preset from `corei7` to `nehalem` so perhaps we could try this? PR welcome.

**Comment by mishugana** [comment]
I'll look at this this weekend

**Comment by lovell** [comment]
The prebuilt binaries for v3.3.0 are now aligned with the x86-64-v2 [microarchitecture](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels).

https://github.com/lovell/farmhash/blob/7778a6a8fba4261d741b48ce1401f8ff5ee31fd8/.github/workflows/ci.yml#L93

Please feel free to re-open if there are still problems relating to this
