### ISSUE TITLE
Node 15 prebuilt

### ISSUE THREAD

**Issue by curtdept** [lovell/farmhash#36]
Could use a bump :)

**Comment by lovell** [comment]
Due to the use of N-API, the latest release should already work with Node.js 15. However you might run into problems with npm v7  as the prebuild-install dependency requires a major version bump.

**Comment by curtdept** [comment]
Should just need a prebuild bump to v88

**Comment by lovell** [comment]
v3.1.1 now available with prebuild-install bumped to v6.0.0 (its breaking change doesn't affect this module).
