### ISSUE TITLE
Specify Pre-Compiled Binaries At Install Time

### ISSUE THREAD

**Issue by kolanos** [lovell/farmhash#38]
Hi,

I am installing farmhash in an Ubuntu environment and deploying to an Azure Functions Windows environment. Is there a way to specify the precompiled binary to use so that Windows is the targeted platform? If so, what would the command be for this?

Right now deploying to Azure I get the following:

```
FailureException: Worker was unable to load function azureLogIngestion: 'Error: \\?\C:\home\site\wwwroot\node_modules\farmhash\build\Release\farmhash.node is not a valid Win32 application
```

Thanks!

**Comment by lovell** [comment]
```sh
npm install --platform=win32 farmhash
```

**Comment by kolanos** [comment]
@lovell Awesome. Thank you. Is it possible to specify more than one platform at a time?

**Comment by lovell** [comment]
No, sorry.
