### ISSUE TITLE
Missing prebuild: true in the github action for most environments.

### ISSUE THREAD

**Issue by Raynos** [lovell/farmhash#45]
I'm trying to debug why this package is not `pnpm` compatible but `leveldown` is `pnpm` compatible and I cannot find out why pnpm wont fetch the prebuilts for farmhash.

I think its because leveldown checks the prebuilts into the npm package (https://www.npmjs.com/package/leveldown?activeTab=code) 

And farmhash fetches them in the build script ( https://www.npmjs.com/package/farmhash?activeTab=code )

**Comment by lovell** [comment]
This module uses Node-API so only one prebuild per platform+arch combo is required, with the oldest supported version of Node.js being used for this purpose.

> I cannot find out why pnpm wont fetch the prebuilts for farmhash.

Is there an error at install time? Could you have enabled the `--ignore-scripts` flag?

**Comment by Raynos** [comment]
I think it's a bug in `pnpm` I don't have ignore scripts. https://github.com/pnpm/pnpm/issues/6395

I did find https://www.npmjs.com/package/bufferutil?activeTab=code as a minimal example of a package that works.

**Comment by Raynos** [comment]
https://github.com/Raynos/pnpm-native-bug-example ; I can't reproduce it. It's a monorepo config issue
