### ISSUE TITLE
[Error] Can't resolve ./build/debug/farmhash.node - Version 3.3.0

### ISSUE THREAD

**Issue by LadyAiss** [lovell/farmhash#46]
Hello,

I am running into the following bug when trying to use farmhash **(version 3.3.0)** in my project:

```
ERROR in ./node_modules/farmhash/index.js 7:11-49
Module not found: Error: Can't resolve './build/Debug/farmhash.node' in '.../node_modules/farmhash'
resolve './build/Debug/farmhash.node' in '.../node_modules/farmhash'
  using description file: .../node_modules/farmhash/package.json (relative path: .)
    using description file: .../node_modules/farmhash/package.json (relative path: ./build/Debug/farmhash.node)
      no extension
        .../node_modules/farmhash/build/Debug/farmhash.node doesn't exist
      .tsx
        .../node_modules/farmhash/build/Debug/farmhash.node.tsx doesn't exist
      .ts
        .../node_modules/farmhash/build/Debug/farmhash.node.ts doesn't exist
      .jsx
        .../node_modules/farmhash/build/Debug/farmhash.node.jsx doesn't exist
      .js
       .../node_modules/farmhash/build/Debug/farmhash.node.js doesn't exist
      .vue
        .../node_modules/farmhash/build/Debug/farmhash.node.vue doesn't exist
      as directory
       .../node_modules/farmhash/build/Debug/farmhash.node doesn't exist
webpack 5.76.0 compiled with 1 error in 20638 ms
```

The error is caused by this following code in `index.js`
```
const farmhash = (function farmhashBinding () {
  try {
    return require('./build/Release/farmhash.node');
  } catch (e) {
    return require('./build/Debug/farmhash.node');
  }
}());
```
because as you can see in the screenshot the referenced file does not exist
![CleanShot 2023-06-01 at 11 31 45](https://github.com/lovell/farmhash/assets/50078699/e1ebbaaf-17da-44d3-8878-0c2a5877d108)

I tried installing previous versions instead but then I ran into this [issue](https://github.com/lovell/farmhash/issues/44) and none of the solutions mentioned there worked for me.

Help will be highly appreciated, since we are really looking forward to using this package 😃

**Comment by lovell** [comment]
Hi, is farmhash included in your webpack `externals` configuration?
```
externals: {
  'farmhash': 'commonjs farmhash'
}
```

**Comment by LadyAiss** [comment]
Hi @lovell,
Thank you for the quick reply, 

Yes, I have added it to the externals configuration and that fixes the first error but then I have the same error as mentioned in this [issue](https://github.com/lovell/farmhash/issues/44)

`ReferenceError: 'require' is not defined`

**Comment by lovell** [comment]
Thanks, I'll close this issue and we can continue to track that problem at #44
