### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by vijayaa** [lovell/farmhash#6]
unable to install on my machine
CentOS release 6.2
node version v0.10.31
i have even tried on CentOS Linux release 7.0.1406 with node version v5.0.0

**Comment by lovell** [comment]
Hello, please can you provide either an error message or the result of running `npm install farmhash`.

**Comment by vijayaa** [comment]
when i tried npm install farmhash it was giving error. i did git clone and then npm install it worked

**Comment by lovell** [comment]
Thanks for the update. You shouldn't have to use `git clone`; farmhash should work straight from npm. If you're able to share details of the error then that might help others with a similar problem.
