### ISSUE TITLE
trouble installing with npm: unrecognised compiler options (-Ofast and -flto)

### ISSUE THREAD

**Issue by TheFive** [lovell/farmhash#7]
Hi,

installing farmhash via NPM on uberspace (shared hoster) results in the following error message:
```
make: Entering directory `..../osmbc/node_modules/farmhash/build'
  CXX(target) Release/obj.target/farmhash/src/upstream/farmhash.o
cc1plus: Fehler: ungültiges Optionsargument »-Ofast«
cc1plus: Fehler: nicht erkannte Kommandozeilenoption »-flto«
make: *** [Release/obj.target/farmhash/src/upstream/farmhash.o] Fehler 1
make: Leaving directory `..../osmbc/node_modules/farmhash/build'
````

What can i do to avoid that ?

Christoph
P.S.
Fehler: ungültiges Optionsargument == Error: invalid option argument
Fehler: nicht erkannte Kommandozeilenoption == error: invalid command line option

**Comment by lovell** [comment]
Hallo, it looks like the version of gcc being used is rather old. The details made available at https://wiki.uberspace.de/development:gcc seem relevant here. Ich hoffe das hilft.

**Comment by TheFive** [comment]
Oh, thanks for quick feedback.

Here my feedback for all that find this thread with a similar problem.
The first (changing the PATH variable to use .4.9.2 version temporary) solution seems to be enough for installation. Of course changing .bashrc to use the "modern" compilers "more often" may be not the worst idea.

-- 
Oder auch Dankeschön :-)

**Comment by TheFive** [comment]
Post Scriptum Comment:

This solves some other error messages i had with npm install and uberspace, but that had no impact on my running software (yet).
